### ISSUE TITLE
KeyError: 'nodeid'

### ISSUE THREAD

**Issue by hddmet** [pytest-dev/pytest-bdd#148]
Hi there,

I am getting KeyError: 'nodeid' when running py.test with pytest-bdd installed.  py.test seems to detect pytest-bdd plugin but it stops running when trying to load it.  I am not sure whether the error is caused by my setup environment or because there is an api incompatibility between the latest py.test and pytest-bdd plugin.  Please help.  If you required additional info, please let me know.

## Traceback

```#!sh
pluggy.py", line 593, in <listcomp>
INTERNALERROR>     args = [all_kwargs[argname] for argname in hook_impl.argnames]
INTERNALERROR> KeyError: 'nodeid'
```

* Details traceback is also included

## My setup environment

OS: centos 7.1    3.10.0-229.14.1.el7.x86_64
virtualenvwrapper
python 3.4.3

### python package list
coverage (4.0)
glob2 (0.4.1)
Mako (1.0.2)
MarkupSafe (0.23)
parse (1.6.6)
parse-type (0.3.4)
pip (7.1.2)
py (1.4.30)
pytest (2.8.0)
pytest-bdd (2.15.0)
setuptools (18.2)
six (1.9.0)
wheel (0.24.0)

## Detailed traceback:

```#!sh
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/aaron/dev/virtualenv/py34-skeleton/lib/python3.4/site-packages/_pytest/main.py", line 86, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/home/aaron/dev/virtualenv/py34-skeleton/lib/python3.4/site-packages/_pytest/config.py", line 829, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/home/aaron/dev/virtualenv/py34-skeleton/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 729, in call_historic
INTERNALERROR>     self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/aaron/dev/virtualenv/py34-skeleton/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/aaron/dev/virtualenv/py34-skeleton/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/home/aaron/dev/virtualenv/py34-skeleton/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/aaron/dev/virtualenv/py34-skeleton/lib/python3.4/site-packages/_pytest/terminal.py", line 47, in pytest_configure
INTERNALERROR>     config.pluginmanager.register(reporter, 'terminalreporter')
INTERNALERROR>   File "/home/aaron/dev/virtualenv/py34-skeleton/lib/python3.4/site-packages/_pytest/config.py", line 206, in register
INTERNALERROR>     ret = super(PytestPluginManager, self).register(plugin, name)
INTERNALERROR>   File "/home/aaron/dev/virtualenv/py34-skeleton/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 370, in register
INTERNALERROR>     hook._maybe_apply_history(hookimpl)
INTERNALERROR>   File "/home/aaron/dev/virtualenv/py34-skeleton/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 747, in _maybe_apply_history
INTERNALERROR>     res = self._hookexec(self, [method], kwargs)
INTERNALERROR>   File "/home/aaron/dev/virtualenv/py34-skeleton/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/aaron/dev/virtualenv/py34-skeleton/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/home/aaron/dev/virtualenv/py34-skeleton/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 593, in execute
INTERNALERROR>     args = [all_kwargs[argname] for argname in hook_impl.argnames]
INTERNALERROR>   File "/home/aaron/dev/virtualenv/py34-skeleton/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 593, in <listcomp>
INTERNALERROR>     args = [all_kwargs[argname] for argname in hook_impl.argnames]
INTERNALERROR> KeyError: 'nodeid'
```

**Comment by rafaduran** [comment]
I'm getting same error, works fine with pytest<2.8.0

**Comment by hddmet** [comment]
Ok Rafael, thanks for the heads-up.  I guess I will use pytest < 2.8.0 for
the time being.

**Comment by bubenkoff** [comment]
yes it's actually pytest issue, still not solved
we can't merge https://github.com/pytest-dev/pytest-bdd/pull/149 because of https://github.com/pytest-dev/pytest/issues/1062

**Comment by hddmet** [comment]
Thanks.

**Comment by hddmet** [comment]
By the way, it is no longer an issue for me since I am using pytest<2.8 as
suggested by Rafael. Therefore, it is fine with me if you prefer to close
this report since #149 already addresses the same issue.

**Comment by olegpidsadnyi** [comment]
This seems to be no longer an issue since pytest is fixed
