### ISSUE TITLE
Python 3.8 crash: TypeError: an integer is required (got type bytes)

### ISSUE THREAD

**Issue by advance512** [pytest-dev/pytest-bdd#354]
When using pytest-bdd with pytest 5.4.1 on Python 3.8.0, the following happens on launch:
```
Traceback (most recent call last):
  File "/home/user/workspace/project/.venv/lib/python3.8/site-packages/_pytest/config/__init__.py", line 105, in main
    config = _prepareconfig(args, plugins)
  File "/home/user/workspace/project/.venv/lib/python3.8/site-packages/_pytest/config/__init__.py", line 257, in _prepareconfig
    return pluginmanager.hook.pytest_cmdline_parse(
  File "/home/user/workspace/project/.venv/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/user/workspace/project/.venv/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/user/workspace/project/.venv/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/home/user/workspace/project/.venv/lib/python3.8/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/home/user/workspace/project/.venv/lib/python3.8/site-packages/_pytest/helpconfig.py", line 90, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/home/user/workspace/project/.venv/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/user/workspace/project/.venv/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/user/workspace/project/.venv/lib/python3.8/site-packages/_pytest/config/__init__.py", line 836, in pytest_cmdline_parse
    self.parse(args)
  File "/home/user/workspace/project/.venv/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1044, in parse
    self._preparse(args, addopts=addopts)
  File "/home/user/workspace/project/.venv/lib/python3.8/site-packages/_pytest/config/__init__.py", line 992, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/home/user/workspace/project/.venv/lib/python3.8/site-packages/pluggy/manager.py", line 299, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/home/user/workspace/project/.venv/lib/python3.8/importlib/metadata.py", line 75, in load
    module = import_module(match.group('module'))
  File "/home/user/workspace/project/.venv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/user/workspace/project/.venv/lib/python3.8/site-packages/_pytest/assertion/rewrite.py", line 152, in exec_module
    exec(co, module.__dict__)
  File "/home/user/workspace/project/.venv/lib/python3.8/site-packages/pytest_bdd/plugin.py", line 26, in <module>
    def trace():
  File "/home/user/workspace/project/.venv/lib/python3.8/site-packages/pytest_bdd/steps.py", line 189, in decorator
    contribute_to_module(
  File "/home/user/workspace/project/.venv/lib/python3.8/site-packages/pytest_bdd/steps.py", line 262, in contribute_to_module
    func = recreate_function(func, module=module)
  File "/home/user/workspace/project/.venv/lib/python3.8/site-packages/pytest_bdd/steps.py", line 246, in recreate_function
    set_code(func, CodeType(*args))
TypeError: an integer is required (got type bytes)
```

This happens in a call to `recreate_function()` with name parameter `'pytestbdd_then_trace'` and the func decorated being this one, in plugin.py:
```
@given('trace')
@when('trace')
@then('trace')
def trace():
    """Enter pytest's pdb trace."""
    pytest.set_trace()
```

The code continues to this line:
```
set_code(func, CodeType(*args))
```
where it calls with args being: 
`[0, 0, 2, 4, 31, b't\x00\x88\x00d\x01d\x02\x8d\x02\x01\x00d\x00S\x00', (None, False, ('pytrace',)), ('fail',), ('args', 'kwargs'), '/home/user/workspace/project/.venv/lib/python3.8/site-packages/pytest_bdd/plugin.py', 'result', 1, b'\x00\x02', ('message',), ()]`
it then fails with the exception:
`(<class 'TypeError'>, TypeError('an integer is required (got type bytes)'), <traceback object at 0x7fb856c14680>)`

This seems related to:
https://github.com/pyinstaller/pyinstaller/issues/4580

Did I reach an edge case using pytest-bdd with Python 3.8.0? Or is there not complete support for Python 3.8?

**Comment by advance512** [comment]
@The-Compiler 
I think you might have the best chance of figuring this out - seems like you worked on the Python 3.8 PR (great job there, by the way).
Did you encounter this issue?

**Comment by advance512** [comment]
@youtux 
I think you might have the best chance of figuring this out - seems like you worked on the Python 3.8 PR #309 (great job there, by the way).
Did you encounter this issue?

Also, @The-Compiler, perhaps you know? I saw you worked on 3.8 #316 

Thank you!

**Comment by advance512** [comment]
I am assuming this has to do with:

> types.CodeType has a new parameter in the second position of the constructor (posonlyargcount) to support positional-only arguments defined in PEP 570. The first argument (argcount) now represents the total number of positional arguments (including positional-only arguments). The new replace() method of types.CodeType can be used to make the code future-proof.
https://docs.python.org/3/whatsnew/3.8.html

They recommend using the `replace()` method of CodeType instead of using it directly:
https://docs.python.org/3/library/types.html#types.CodeType.replace

I will try to tackle it tomorrow (by finding what to put in the second position of the constructor), unless if you two know of a quick solution.

**Comment by advance512** [comment]
Hmm, yeah, this actually worked:

```
    argnames = [
        "co_argcount", "co_posonlyargcount", "co_nlocals", "co_stacksize", "co_flags", "co_code", "co_consts", "co_names",
        "co_varnames", "co_filename", "co_name", "co_firstlineno", "co_lnotab", "co_freevars", "co_cellvars",
    ]
```
^^ Added `"co_posonlyargcount"`

```
        elif arg == "co_posonlyargcount":
            args.append(0)
```
^^ Added this to the `for arg in argnames:` loop, but this is because I know none of my code uses positional-only arguments. I am sure in a real fix this won't be enough.

This allowed me to proceed with tests, at least, temporarily.

**Comment by The-Compiler** [comment]
What version of pytest-bdd are you using?

**Comment by advance512** [comment]
pytest-bdd==3.2.1

**Comment by The-Compiler** [comment]
The code referred to by your stacktrace [doesn't exist](https://github.com/pytest-dev/pytest-bdd/blob/3.2.1/pytest_bdd/steps.py) in 3.2.1, so I'm pretty sure you're running an older version before #309.

**Comment by advance512** [comment]
Though I was certain I was installing pytest-bdd 3.2.1, another dependency installed pytest-bdd 3.0.0 and overwrote 3.2.1. So I guess this issue is incorrect.

Thanks. :)
