### ISSUE TITLE
Cross browser testing with pytest-bdd

### ISSUE THREAD

**Issue by iamtech123** [pytest-dev/pytest-bdd#434]
I like to execute my test cases with more than one type of browser(chrome and firefox) at the same time.

Cross browser testing is successful with pytest using below code

@pytest.fixture(params=["chrome", "firefox"],scope="class")
def driver_init(request):
    from selenium import webdriver
    if request.param == "chrome":
        web_driver = webdriver.Chrome()
    if request.param == "firefox":
        web_driver = webdriver.Firefox()
    request.cls.driver = web_driver
    yield
    web_driver.close()

How to implement the same using pytest-bdd, I have tried below but it didnt work

@pytest.fixture(params=["chrome", "firefox"],scope="class")
def driver(request):
    from selenium import webdriver
    if request.param == "chrome":
        web_driver = webdriver.Chrome()
    if request.param == "firefox":
        web_driver = webdriver.Firefox()
    yield
    web_driver.close()

Referred in step def like below

@given('I am in google page')
def step_function(driver_init):

error message

    @pytest.mark.usefixtures(*function_args)
    def scenario_wrapper(request):
>       _execute_scenario(feature, scenario, request)

c:\users\user1\.virtualenvs\python-pytest-bdd-8g8otlzx\lib\site-packages\pytest_bdd\scenario.py:165:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
c:\users\user1\.virtualenvs\python-pytest-bdd-8g8otlzx\lib\site-packages\pytest_bdd\scenario.py:136: in _execute_scenario
    _execute_step_function(request, scenario, step, step_func)
c:\users\user1\.virtualenvs\python-pytest-bdd-8g8otlzx\lib\site-packages\pytest_bdd\scenario.py:106: in _execute_step_function    
    return_value = step_func(**kwargs)
_______________________________________________________ test_perform_search _______________________________________________________ 
'Function' object has no attribute 'callspec'

During handling of the above exception, another exception occurred:
The requested fixture has no parameter defined for test:
    tests/step_defs/test_bdd_ui.py::test_perform_search

Requested fixture 'driver' defined in:
tests\step_defs\conftest.py:17

Requested here:
c:\users\user1\.virtualenvs\python-pytest-bdd-8g8otlzx\lib\site-packages\pytest_bdd\scenario.py:100
------------------------------------------------------ Captured stdout call ------------------------------------------------------- 
_____________________________________________ test_perform_search_and_validate_count ______________________________________________ 
'Function' object has no attribute 'callspec'

During handling of the above exception, another exception occurred:
The requested fixture has no parameter defined for test:
    tests/step_defs/test_bdd_ui.py::test_perform_search_and_validate_count

Requested fixture 'driver' defined in:
tests\step_defs\conftest.py:17

Requested here:
c:\users\user1\.virtualenvs\python-pytest-bdd-8g8otlzx\lib\site-packages\pytest_bdd\scenario.py:100
------------------------------------------------------ Captured stdout call ------------------------------------------------------- 
_____________________________________ test_perform_search _______________________________________________________ 
'Function' object has no attribute 'callspec'

During handling of the above exception, another exception occurred:
The requested fixture has no parameter defined for test:
    tests/step_defs/test_bdd_ui_2.py::test_perform_search

Requested fixture 'driver' defined in:
tests\step_defs\conftest.py:17

Requested here:
c:\users\user1\.virtualenvs\python-pytest-bdd-8g8otlzx\lib\site-packages\pytest_bdd\scenario.py:100
------------------------------------------------------ Captured stdout call ------------------------------------------------------- 
_____________________________________________ test_perform_search_and_validate_count ______________________________________________ 
'Function' object has no attribute 'callspec'

During handling of the above exception, another exception occurred:
The requested fixture has no parameter defined for test:
    tests/step_defs/test_bdd_ui_2.py::test_perform_search_and_validate_count

Requested fixture 'driver' defined in:
tests\step_defs\conftest.py:17

Requested here:
c:\users\user1\.virtualenvs\python-pytest-bdd-8g8otlzx\lib\site-packages\pytest_bdd\scenario.py:100
------------------------------------------------------ Captured stdout call ------------------------------------------------------- 
Traceback (most recent call last):
  File "c:\python377\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python377\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user1\.virtualenvs\python-pytest-bdd-8G8otLZX\Scripts\pytest.exe\__main__.py", line 7, in <module>
  File "c:\users\user1\.virtualenvs\python-pytest-bdd-8g8otlzx\lib\site-packages\_pytest\config\__init__.py", line 185, in console_main
    code = main()
  File "c:\users\user1\.virtualenvs\python-pytest-bdd-8g8otlzx\lib\site-packages\_pytest\config\__init__.py", line 163, in main   
    config=config
  File "c:\users\user1\.virtualenvs\python-pytest-bdd-8g8otlzx\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\users\user1\.virtualenvs\python-pytest-bdd-8g8otlzx\lib\site-packages\pluggy\manager.py", line 93, in _hookexec        
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\users\user1\.virtualenvs\python-pytest-bdd-8g8otlzx\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\users\user1\.virtualenvs\python-pytest-bdd-8g8otlzx\lib\site-packages\pluggy\callers.py", line 208, in _multicall      
    return outcome.get_result()
  File "c:\users\user1\.virtualenvs\python-pytest-bdd-8g8otlzx\lib\site-packages\pluggy\callers.py", line 80, in get_result       
    raise ex[1].with_traceback(ex[2])
  File "c:\users\user1\.virtualenvs\python-pytest-bdd-8g8otlzx\lib\site-packages\pluggy\callers.py", line 187, in _multicall      
    res = hook_impl.function(*args)
  File "c:\users\user1\.virtualenvs\python-pytest-bdd-8g8otlzx\lib\site-packages\_pytest\main.py", line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "c:\users\user1\.virtualenvs\python-pytest-bdd-8g8otlzx\lib\site-packages\_pytest\main.py", line 305, in wrap_session      
    session=session, exitstatus=session.exitstatus
  File "c:\users\user1\.virtualenvs\python-pytest-bdd-8g8otlzx\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\users\user1\.virtualenvs\python-pytest-bdd-8g8otlzx\lib\site-packages\pluggy\manager.py", line 93, in _hookexec        
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\users\user1\.virtualenvs\python-pytest-bdd-8g8otlzx\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\users\user1\.virtualenvs\python-pytest-bdd-8g8otlzx\lib\site-packages\pluggy\callers.py", line 203, in _multicall
    gen.send(outcome)
  File "c:\users\user1\.virtualenvs\python-pytest-bdd-8g8otlzx\lib\site-packages\_pytest\terminal.py", line 814, in pytest_sessionfinish
    terminalreporter=self, exitstatus=exitstatus, config=self.config
  File "c:\users\user1\.virtualenvs\python-pytest-bdd-8g8otlzx\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\users\user1\.virtualenvs\python-pytest-bdd-8g8otlzx\lib\site-packages\pluggy\manager.py", line 93, in _hookexec        
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\users\user1\.virtualenvs\python-pytest-bdd-8g8otlzx\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\users\user1\.virtualenvs\python-pytest-bdd-8g8otlzx\lib\site-packages\pluggy\callers.py", line 203, in _multicall      
    gen.send(outcome)
  File "c:\users\user1\.virtualenvs\python-pytest-bdd-8g8otlzx\lib\site-packages\pytest_html_reporter\plugin.py", line 267, in pytest_terminal_summary
    self.update_archives_template(base)
  File "c:\users\user1\.virtualenvs\python-pytest-bdd-8g8otlzx\lib\site-packages\pytest_html_reporter\plugin.py", line 773, in update_archives_template
    self.load_archive(f, value='history')
  File "c:\users\user1\.virtualenvs\python-pytest-bdd-8g8otlzx\lib\site-packages\pytest_html_reporter\plugin.py", line 791, in load_archive
    suite_highlights(data)
  File "c:\users\user1\.virtualenvs\python-pytest-bdd-8g8otlzx\lib\site-packages\pytest_html_reporter\plugin.py", line 108, in suite_highlights
    if data['content']['suites'][i]['status']['total_fail'] == 0:
KeyError: 'total_fail'

Could you help.

**Comment by olegpidsadnyi** [comment]
Maybe defining the driver fixture globally (test module or conftest) as autouse=True could help. Theoretically it might be added to every scenario, which has to multiply them.
